openapi: 3.0.0
info:
  title: Cinema API
  description: API for managing a cinema system
  version: "1.0"
servers:
  - url: 'http://localhost:3000/'
paths:
  /cinema-rooms:
    post:
      summary: Create a new cinema room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CinemaRoom'
      responses:
        '201':
          description: Successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CinemaRoom'
    get:
      summary: Get all cinema rooms
      responses:
        '200':
          description: A list of cinema rooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CinemaRoom'
  /cinema-rooms/{id}:
    get:
      summary: Get a specific cinema room
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cinema room details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CinemaRoom'
    put:
      summary: Update a specific cinema room
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CinemaRoom'
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CinemaRoom'
    delete:
      summary: Delete a specific cinema room
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successfully deleted
  /cinema-rooms/{id}/schedule:
    get:
      summary: Get the schedule for a specific cinema room
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cinema room schedule
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Session'
  /sessions:
    post:
      summary: Add a new session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Session'
      responses:
        '201':
          description: Successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
    get:
      summary: Get all sessions
      responses:
        '200':
          description: List of all sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Session'
  /sessions/{id}:
    get:
      summary: Get a specific session
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Session details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
    put:
      summary: Update a specific session
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Session'
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
    delete:
      summary: Delete a specific session
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successfully deleted
  /movies:
    post:
      summary: Add a new movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
      responses:
        '201':
          description: Successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
    get:
      summary: Get all movies
      responses:
        '200':
          description: List of all movies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
  /movies/{id}:
    get:
      summary: Get a specific movie
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Movie details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
    put:
      summary: Update a specific movie
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Movie'
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
    delete:
      summary: Delete a specific movie
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successfully deleted
components:
  schemas:
    CinemaRoom:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        images:
          type: array
          items:
            type: string
        type:
          type: string
        capacity:
          type: integer
        accessibility:
          type: boolean
    Session:
      type: object
      properties:
        movieId:
          type: string
        roomId:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
    Movie:
      type: object
      properties:
        title:
          type: string
        duration:
          type: integer
        description:
          type: string
        genre:
          type: array
          items:
            type: string